import path from "node:path";
import { defineConfig } from "vitest/config";
import react from "@vitejs/plugin-react";

const SRC_DIR = path.resolve(__dirname, "./src");

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      // @/ alias used by feature components
      "@": SRC_DIR,
      // Bare "src/..." imports generated by shadcn CLI when aliases.ui = "src/components/ui"
      "src": SRC_DIR,
    },
  },
  css: {
    // Disable PostCSS/Tailwind processing in tests — not needed for unit tests
    // and avoids the ts-node requirement for postcss.config.ts
    postcss: {},
  },
  test: {
    environment: "jsdom",
    globals: true,
    setupFiles: [],
  },
});
